spring:
  data:
    mongodb:
      port: 0
      database: test
      host: localhost
      #port: 27017
      #database: awesomeMongo

  mvc:
    hiddenmethod:
      filter:
        enabled: true

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 4.0.2

mongock:
#  runner-type: "ApplicationRunner" # default
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.hw.changelogs
  mongo-db:
    write-concern:
      journal: false
    read-concern: local
