spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/demoDB
    username: usr
    password: pwd
  flyway:
    enabled: true


  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
#    show-sql: true

  data:
    rest:
      basePath: /datarest

management:
  endpoints:
    web:
      exposure:
        include: metrics,health,logfile
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true

logging:
  level:
    root:
      info
  file:
    name:
      ./log/books.log